### ISSUE TITLE
Squirrel Roadmap

### ISSUE THREAD

**Issue by doug-martin** [lann/squirrel#42]
Hi,

We were looking at using Squirrel for our project but are unsure about the roadmap and features that will/will not be added and had a list items that would be required in order for us to use but are unsure if you feel they are out of the scope of your project or if you have purposefully not added some of them for philosophical reasons.

* Parameter Interpolation - Would require adapter specific settings
   * Reduces Roundtrips to server, currently depending on the driver it makes one request to prepare the statement then executes
   * Would be nice to also explicitly create a prepared statement
* Identifier support - Would Require adapter specific settings
	* Prevents unexpected side effects like case sensitive tables or schemas from being ignored, also if the schema or table contains non standard characters like `-` not quoting would not work for some dbs	
* More robust expression support to support parameter interpolation.
	* Right now If I want to do something like COALESCE and didnt want the statement to be prepared, I would have to encode the value manually
	* Would require more expressions with things like SqlFunctions, Identifer expressions, literals etc..
	* Or interpolation of placeholder values if available
* Scanning into structs/slices
	* Right now it appears that I would have to scan results manually
	* This might require db specific adapters depending on values returned (i.e. postgres doesnt return last insert id), if I wanted to get that I would have create a suffix with a returning clause, and execute a query, while on mysql I could run exec. 
* Support for multi insert with structs or maps
   * The `db` tag seems to be fairly common would be nice If I would pass in a struct or a slice of structs to generate insert statements, and a single struct for updates
* Support for subqueries, and possible auto aliasing for the subselect depending on the number of sources that are in the FROM clause
* Other Possiblities
	* A Count method
	* A Pluck method for plucking a single field and scanning into a slice 
	* Support for different date types
		* YEAR, TIME, TIMESTAMP, DATETIME etc
		* Would require adapter specific settings or user specified date formats
	* Cast support for identifier types
	* So I could do something like `I("created").Cast("DATE").Eq(Date(time.Now()))
* Trace logging of sql statements
* More robust/explicit transaction support

I completely understand if you feel these requests are outside of the scope of the project, as some of the requests could require a large refactor. As it appears right now squirrel seems less opinionated and gives more control to the developer about how they want a statement expressed and some of these requests could take away some of that.

-Doug

**Comment by doug-martin** [comment]
Also I should note that some of these may already exist and I just missed them, if so just let me know thanks!

**Comment by lann** [comment]
Generally speaking, none of this is likely to be done (by me) any time soon. The product I was writing this for has been a casualty of acquisition and I am not currently writing any Go for work. I would be happy to support a fork.

Philosophically:

The ORMy stuff is probably going to stay out of scope - squirrel is meant to be primarily a SQL generation DSL and I'd like to keep it focused on that, though it should be relatively straightforward to combine or wrap it with a separate ORM. One of my coworkers has an ORM based on it as an example: https://github.com/technosophos/structable

Adapter-specific features are probably not going to happen in v1. I've considered various ways of doing them and I think they are incompatible with the current architecture. They would definitely be top priorities in a (backwards-incompatible) v2, along with a way to extend syntax (which probably means code generation, sadly).

**Comment by doug-martin** [comment]
Thanks for the quick response and I totally understand, I mostly assumed as much just wanted to check! Thanks again -Doug
