### ISSUE TITLE
Feature Request: QueryRow() on UpdateBuilder

### ISSUE THREAD

**Issue by ngauthier** [lann/squirrel#48]
When Inserting, I can do this:

```go
return psql().
	Insert(tableName).
	Columns(columns...).
	Values(values...).
	Suffix(`RETURNING "id"`).
	RunWith(db).
	QueryRow().
	Scan(&obj.ID)
```

But I cannot do a similar thing in update. This is not possible:

```go
return psql().
	Update(tableName).
	Set("foo", "bar")
	Suffix(`RETURNING "foo"`).
	RunWith(db).
	QueryRow().
	Scan(&obj.Foo)
```

Which is a nice way to ensure that I keep my struct up to date with changes.

My workaround is this:

```go
rows, err := sq.QueryWith(db, psql().
        Update(tableName).
        Set("foo", "bar").
        Where(sq.Eq{"id": id}).
        Suffix(`RETURNING "foo"`),
)
if err != nil {
        return err
}
defer rows.Close()
rows.Next()
return rows.Scan(&obj.Foo)
```

Is QueryRow on Update (and also, Query) something we could add to squirrel?

Thanks!

**Comment by lann** [comment]
I've decided against adding specific non-standard SQL features without some kind of plugin mechanism (i.e. a "squirrel/psql" plugin with postgres-specific features). At this point I'm waiting on some kind of standard generic/codegen system for Go to implement plugins (though I'd be happy to look at other solutions).

For your workaround, there is a `QueryRowWith` function that would simplify it.

**Comment by ngauthier** [comment]
ah thanks, QueryRowWith will help a lot. I am happy to just use a helper in my own code. Thanks for explaining.

**Comment by ngauthier** [comment]
So it looks like QueryRowWith doesn't work with UpdateBuilder because it's not a QueryRower (because it doesn't implement QueryRow). I am still happy using a helper. Do you think it's still inappropriate to add only QueryRow to UpdateBuilder?

**Comment by ngauthier** [comment]
If it helps clarify, this is a completely generic helper:

```go
type sqlQueryRower struct {
	*sql.DB
}

func (s *sqlQueryRower) QueryRow(str string, args ...interface{}) sq.RowScanner {
	return s.DB.QueryRow(str, args...)
}

// Now I can:
return sq.QueryRowWith(&sqlQueryRower{db}, query)
```

It's only a signature mismatch that does not allow QueryRowWith to take a *sql.DB. Anything we can do here?

**Comment by lann** [comment]
This is one of the unfortunate problems with database/sql - they used a concrete struct type for Row instead of an interface, so theres no way to match the signature with a different type.

**Comment by ngauthier** [comment]
Could we add a constructor to Squirrel called NewQueryRower, like this:


```go
func NewQueryRower(db *sql.DB) QueryRower {
  return &sqlQueryRower{db}
}
```

Using the type and function above, and leave them internal, and only expose the constructor? It will show up in the docs next to QueryRowWith and be a clear path to use QueryRowWith with a sql db and any Sqlizer.

I am happy to make this PR if you like the idea.

**Comment by ngauthier** [comment]
Also thank you very much for being responsive and available!
